version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: .
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/authdb"
      JWT_SECRET: "supersecret"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  postgres_data:
